---

- name: "Instlacja narzedzi uzytkownika noda boaccess"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Instalacja narzedzi uzytkownika" 
      yum:
        name: 
          - nano
          - less
          - vim
          - mc
          - gawk
          - perl
          - unzip
          - screen
          - tcsh
        state: present
        update_cache: yes
