---
- name: "Instlacja systemu kolejkowego SGE"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Instalacja pakietow systemu kolejkowego SGE" 
      yum:
        name:
          - hwloc 
          - /tmp/jemalloc-3.6.0-1.el7.x86_64.rpm
        state: present
        update_cache: yes
    - name: "DO POPRAWY - Obejcie, tworzenie linku /opt/sge do /usr/local/sge"
      file:
        src: /opt/sge
        dest: /usr/local/sge
        state: link
        force: yes
    - name: "Zakladanie uzytkownika sgeadmin"
      shell: groupadd -g 998 -r sgeadmin && useradd -c "SOGE admin user" -g 998 -u 999 sgeadmin -r
    - name: "Kasowanie plikow rpm systemu SGE" 
      shell: rm -f /tmp/*.rpm
