---

- name: "Instalacja oprgramowania monit do monitorowania procesó∑ kontenera"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Dodatkowe repozytorium EPEL" 
      yum:
        name: 
          - epel-release.noarch
        state: present
        update_cache: yes
    - name: "Instalacja monit" 
      yum:
        name: monit
        state: present