---

- name: "Instlacja klienta MFS"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Sciaganie RPM-GPG-KEY-MooseFS"
      get_url:
        url: http://ppa.moosefs.com/RPM-GPG-KEY-MooseFS
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-MooseFS
    - name: "Sciaganie MooseFS.repo"
      get_url:
        url: http://ppa.moosefs.com/MooseFS-3-el7.repo
        dest: /etc/yum.repos.d/MooseFS.repo
    - name: "Ustawienie wersji klienta"
      replace:
        path: /etc/yum.repos.d/MooseFS.repo
        regexp: 'moosefs-3'
        replace: 3.0.100 
    - name: "Instalacja moosefs-pro-client" 
      yum:
        name: 
          - moosefs-pro-client
        state: present
        update_cache: yes
